[package]
name = "periodic-table"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui = { version = "0.29.0", features = ["crossterm"] }
