use crate::element::{Element, ElementCategory};

pub fn load_elements() -> Vec<Element> {
    vec![
        // Period 1
        Element {
            number: 1,
            symbol: "H".to_string(),
            name: "Hydrogen".to_string(),
            mass: 1.008,
            category: ElementCategory::Nonmetal,
            position: (1, 1),
            description: "Lightest element. Highly flammable diatomic gas. Most abundant element in the universe.".to_string(),
        },
        Element {
            number: 2,
            symbol: "He".to_string(),
            name: "Helium".to_string(),
            mass: 4.0026,
            category: ElementCategory::NobleGas,
            position: (1, 18),
            description: "Colorless, odorless, tasteless, non-toxic, inert, monatomic gas. Second lightest and second most abundant element in the universe.".to_string(),
        },
        // Period 2
        Element {
            number: 3,
            symbol: "Li".to_string(),
            name: "Lithium".to_string(),
            mass: 6.94,
            category: ElementCategory::AlkaliMetal,
            position: (2, 1),
            description: "Soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.".to_string(),
        },
        Element {
            number: 4,
            symbol: "Be".to_string(),
            name: "Beryllium".to_string(),
            mass: 9.0122,
            category: ElementCategory::AlkalineEarthMetal,
            position: (2, 2),
            description: "Relatively rare element. Steel-gray, strong, lightweight and brittle alkaline earth metal.".to_string(),
        },
        Element {
            number: 5,
            symbol: "B".to_string(),
            name: "Boron".to_string(),
            mass: 10.81,
            category: ElementCategory::Metalloid,
            position: (2, 13),
            description: "Semiconductor with properties between metals and non-metals. Essential for plant growth.".to_string(),
        },
        Element {
            number: 6,
            symbol: "C".to_string(),
            name: "Carbon".to_string(),
            mass: 12.011,
            category: ElementCategory::Nonmetal,
            position: (2, 14),
            description: "Basis for all known life. Fourth most abundant element in the universe by mass. Occurs in many forms including diamond and graphite.".to_string(),
        },
        Element {
            number: 7,
            symbol: "N".to_string(),
            name: "Nitrogen".to_string(),
            mass: 14.007,
            category: ElementCategory::Nonmetal,
            position: (2, 15),
            description: "Colorless, odorless, tasteless gas that makes up 78% of Earth's atmosphere. Essential component of proteins and nucleic acids.".to_string(),
        },
        Element {
            number: 8,
            symbol: "O".to_string(),
            name: "Oxygen".to_string(),
            mass: 15.999,
            category: ElementCategory::Nonmetal,
            position: (2, 16),
            description: "Highly reactive nonmetal that forms compounds with almost all other elements. Essential for respiration in most living organisms.".to_string(),
        },
        Element {
            number: 9,
            symbol: "F".to_string(),
            name: "Fluorine".to_string(),
            mass: 18.998,
            category: ElementCategory::Halogen,
            position: (2, 17),
            description: "Extremely reactive pale yellow diatomic gas. Most electronegative element. Reacts with almost all organic and inorganic substances.".to_string(),
        },
        Element {
            number: 10,
            symbol: "Ne".to_string(),
            name: "Neon".to_string(),
            mass: 20.180,
            category: ElementCategory::NobleGas,
            position: (2, 18),
            description: "Colorless, odorless, inert monatomic gas. Fifth most abundant element in the universe. Known for its bright red-orange glow in signs.".to_string(),
        },
        // Period 3
        Element {
            number: 11,
            symbol: "Na".to_string(),
            name: "Sodium".to_string(),
            mass: 22.990,
            category: ElementCategory::AlkaliMetal,
            position: (3, 1),
            description: "Soft, highly reactive silvery metal. Essential for nerve and muscle function in animals.".to_string(),
        },
        Element {
            number: 12,
            symbol: "Mg".to_string(),
            name: "Magnesium".to_string(),
            mass: 24.305,
            category: ElementCategory::AlkalineEarthMetal,
            position: (3, 2),
            description: "Lightweight, silvery-white metal. Essential element for all life. Important for many enzymes, especially those using ATP.".to_string(),
        },
        Element {
            number: 13,
            symbol: "Al".to_string(),
            name: "Aluminum".to_string(),
            mass: 26.982,
            category: ElementCategory::PostTransitionMetal,
            position: (3, 13),
            description: "Low density, corrosion-resistant metal. Most abundant metal in Earth's crust. Used in alloys, packaging, and aerospace.".to_string(),
        },
        Element {
            number: 14,
            symbol: "Si".to_string(),
            name: "Silicon".to_string(),
            mass: 28.085,
            category: ElementCategory::Metalloid,
            position: (3, 14),
            description: "Second most abundant element in Earth's crust. Crucial for semiconductor industry and glass manufacturing.".to_string(),
        },
        Element {
            number: 15,
            symbol: "P".to_string(),
            name: "Phosphorus".to_string(),
            mass: 30.974,
            category: ElementCategory::Nonmetal,
            position: (3, 15),
            description: "Essential for life, particularly DNA, RNA, and ATP. Used in fertilizers, detergents, and matches.".to_string(),
        },
        Element {
            number: 16,
            symbol: "S".to_string(),
            name: "Sulfur".to_string(),
            mass: 32.06,
            category: ElementCategory::Nonmetal,
            position: (3, 16),
            description: "Yellow crystalline solid. Essential for all life, present in two amino acids. Used in fertilizers, gunpowder, and vulcanization of rubber.".to_string(),
        },
        Element {
            number: 17,
            symbol: "Cl".to_string(),
            name: "Chlorine".to_string(),
            mass: 35.45,
            category: ElementCategory::Halogen,
            position: (3, 17),
            description: "Yellow-green gas. Used for water purification, bleaching, and in PVC production. Essential for many biological processes.".to_string(),
        },
        Element {
            number: 18,
            symbol: "Ar".to_string(),
            name: "Argon".to_string(),
            mass: 39.948,
            category: ElementCategory::NobleGas,
            position: (3, 18),
            description: "Colorless, odorless noble gas. Third most abundant gas in Earth's atmosphere. Used in welding and lighting.".to_string(),
        },
        // Period 4
        Element {
            number: 19,
            symbol: "K".to_string(),
            name: "Potassium".to_string(),
            mass: 39.098,
            category: ElementCategory::AlkaliMetal,
            position: (4, 1),
            description: "Soft, silvery-white metal. Essential for plant and animal life. Critical for nerve function.".to_string(),
        },
        Element {
            number: 20,
            symbol: "Ca".to_string(),
            name: "Calcium".to_string(),
            mass: 40.078,
            category: ElementCategory::AlkalineEarthMetal,
            position: (4, 2),
            description: "Soft, gray alkaline earth metal. Essential for bones, teeth and shells. Fifth most abundant element in Earth's crust.".to_string(),
        },
        Element {
            number: 21,
            symbol: "Sc".to_string(),
            name: "Scandium".to_string(),
            mass: 44.956,
            category: ElementCategory::TransitionMetal,
            position: (4, 3),
            description: "Silvery-white metallic transition metal. Used in aerospace components and high-intensity lights.".to_string(),
        },
        Element {
            number: 22,
            symbol: "Ti".to_string(),
            name: "Titanium".to_string(),
            mass: 47.867,
            category: ElementCategory::TransitionMetal,
            position: (4, 4),
            description: "Strong, lightweight, corrosion-resistant transition metal. Used in aerospace, medical implants, and pigments.".to_string(),
        },
        Element {
            number: 23,
            symbol: "V".to_string(),
            name: "Vanadium".to_string(),
            mass: 50.942,
            category: ElementCategory::TransitionMetal,
            position: (4, 5),
            description: "Rare, soft, ductile transition metal. Used in steel alloys for high strength applications.".to_string(),
        },
        Element {
            number: 24,
            symbol: "Cr".to_string(),
            name: "Chromium".to_string(),
            mass: 51.996,
            category: ElementCategory::TransitionMetal,
            position: (4, 6),
            description: "Hard, lustrous, steel-gray metal. Used in stainless steel and chrome plating. Essential trace element for humans.".to_string(),
        },
        Element {
            number: 25,
            symbol: "Mn".to_string(),
            name: "Manganese".to_string(),
            mass: 54.938,
            category: ElementCategory::TransitionMetal,
            position: (4, 7),
            description: "Hard, brittle transition metal. Essential trace nutrient and used in steel production.".to_string(),
        },
        Element {
            number: 26,
            symbol: "Fe".to_string(),
            name: "Iron".to_string(),
            mass: 55.845,
            category: ElementCategory::TransitionMetal,
            position: (4, 8),
            description: "Most common element on Earth by mass. Forms most of Earth's inner and outer core. Essential for hemoglobin in blood.".to_string(),
        },
        Element {
            number: 27,
            symbol: "Co".to_string(),
            name: "Cobalt".to_string(),
            mass: 58.933,
            category: ElementCategory::TransitionMetal,
            position: (4, 9),
            description: "Hard, lustrous, silver-gray metal. Used in magnets, batteries, and as a pigment. Essential for vitamin B12.".to_string(),
        },
        Element {
            number: 28,
            symbol: "Ni".to_string(),
            name: "Nickel".to_string(),
            mass: 58.693,
            category: ElementCategory::TransitionMetal,
            position: (4, 10),
            description: "Silvery-white, hard, ductile metal. Used in alloys, batteries, and electroplating.".to_string(),
        },
        Element {
            number: 29,
            symbol: "Cu".to_string(),
            name: "Copper".to_string(),
            mass: 63.546,
            category: ElementCategory::TransitionMetal,
            position: (4, 11),
            description: "Ductile metal with high thermal and electrical conductivity. Used extensively in electrical wiring, plumbing, and coinage.".to_string(),
        },
        Element {
            number: 30,
            symbol: "Zn".to_string(),
            name: "Zinc".to_string(),
            mass: 65.38,
            category: ElementCategory::TransitionMetal,
            position: (4, 12),
            description: "Brittle, bluish-white metal. Used for galvanizing iron and in alloys like brass. Essential trace element for many organisms.".to_string(),
        },
        Element {
            number: 31,
            symbol: "Ga".to_string(),
            name: "Gallium".to_string(),
            mass: 69.723,
            category: ElementCategory::PostTransitionMetal,
            position: (4, 13),
            description: "Soft, silvery metal that melts near room temperature. Used in semiconductors and high-temperature thermometers.".to_string(),
        },
        Element {
            number: 32,
            symbol: "Ge".to_string(),
            name: "Germanium".to_string(),
            mass: 72.630,
            category: ElementCategory::Metalloid,
            position: (4, 14),
            description: "Lustrous, hard-brittle, grayish-white metalloid. Important semiconductor material used in transistors and solar cells.".to_string(),
        },
        Element {
            number: 33,
            symbol: "As".to_string(),
            name: "Arsenic".to_string(),
            mass: 74.922,
            category: ElementCategory::Metalloid,
            position: (4, 15),
            description: "Metalloid that exists in various allotropes. Used in semiconductors, wood preservatives, and pesticides.".to_string(),
        },
        Element {
            number: 34,
            symbol: "Se".to_string(),
            name: "Selenium".to_string(),
            mass: 78.971,
            category: ElementCategory::Nonmetal,
            position: (4, 16),
            description: "Nonmetal with properties similar to sulfur. Used in electronics, glass manufacturing, and essential trace element for humans and animals.".to_string(),
        },
        Element {
            number: 35,
            symbol: "Br".to_string(),
            name: "Bromine".to_string(),
            mass: 79.904,
            category: ElementCategory::Halogen,
            position: (4, 17),
            description: "Red-brown liquid at room temperature. Used in flame retardants, water purification, and pharmaceuticals.".to_string(),
        },
        Element {
            number: 36,
            symbol: "Kr".to_string(),
            name: "Krypton".to_string(),
            mass: 83.798,
            category: ElementCategory::NobleGas,
            position: (4, 18),
            description: "Colorless, odorless noble gas. Used in lighting and as a high-performance window insulator.".to_string(),
        },
        // Period 5
        Element {
            number: 37,
            symbol: "Rb".to_string(),
            name: "Rubidium".to_string(),
            mass: 85.468,
            category: ElementCategory::AlkaliMetal,
            position: (5, 1),
            description: "Soft, silvery-white metallic element. Highly reactive and used in atomic clocks and vacuum tubes.".to_string(),
        },
        Element {
            number: 38,
            symbol: "Sr".to_string(),
            name: "Strontium".to_string(),
            mass: 87.62,
            category: ElementCategory::AlkalineEarthMetal,
            position: (5, 2),
            description: "Soft, silvery alkaline earth metal. Used in fireworks for red color and absorbed by bones like calcium.".to_string(),
        },
        Element {
            number: 39,
            symbol: "Y".to_string(),
            name: "Yttrium".to_string(),
            mass: 88.906,
            category: ElementCategory::TransitionMetal,
            position: (5, 3),
            description: "Silvery-metallic transition metal. Used in LED and OLED lighting, as well as in superconductors.".to_string(),
        },
        Element {
            number: 40,
            symbol: "Zr".to_string(),
            name: "Zirconium".to_string(),
            mass: 91.224,
            category: ElementCategory::TransitionMetal,
            position: (5, 4),
            description: "Silvery, corrosion-resistant metal. Used in nuclear reactor cladding, ceramics, and as a chemical catalyst.".to_string(),
        },
        Element {
            number: 41,
            symbol: "Nb".to_string(),
            name: "Niobium".to_string(),
            mass: 92.906,
            category: ElementCategory::TransitionMetal,
            position: (5, 5),
            description: "Soft, gray, ductile transition metal. Used in strong steel alloys and superconductors.".to_string(),
        },
        Element {
            number: 42,
            symbol: "Mo".to_string(),
            name: "Molybdenum".to_string(),
            mass: 95.95,
            category: ElementCategory::TransitionMetal,
            position: (5, 6),
            description: "Silvery metal with high melting point. Used in high-strength steel alloys and catalysts. Essential trace element for many organisms.".to_string(),
        },
        Element {
            number: 43,
            symbol: "Tc".to_string(),
            name: "Technetium".to_string(),
            mass: 98.0,
            category: ElementCategory::TransitionMetal,
            position: (5, 7),
            description: "Radioactive transition metal not found naturally on Earth. Used in nuclear medicine for imaging and diagnostics.".to_string(),
        },
        Element {
            number: 44,
            symbol: "Ru".to_string(),
            name: "Ruthenium".to_string(),
            mass: 101.07,
            category: ElementCategory::TransitionMetal,
            position: (5, 8),
            description: "Hard, rare transition metal. Used in wear-resistant electrical contacts and thick-film resistors.".to_string(),
        },
        Element {
            number: 45,
            symbol: "Rh".to_string(),
            name: "Rhodium".to_string(),
            mass: 102.91,
            category: ElementCategory::TransitionMetal,
            position: (5, 9),
            description: "Rare, silvery-white, hard transition metal. Used in catalytic converters and as a reflective coating.".to_string(),
        },
        Element {
            number: 46,
            symbol: "Pd".to_string(),
            name: "Palladium".to_string(),
            mass: 106.42,
            category: ElementCategory::TransitionMetal,
            position: (5, 10),
            description: "Rare, lustrous silvery-white metal. Used in catalytic converters, electrical contacts, and jewelry.".to_string(),
        },
        Element {
            number: 47,
            symbol: "Ag".to_string(),
            name: "Silver".to_string(),
            mass: 107.87,
            category: ElementCategory::TransitionMetal,
            position: (5, 11),
            description: "Soft, white, lustrous transition metal with the highest electrical and thermal conductivity of any metal. Used in jewelry, utensils, and electronics.".to_string(),
        },
        Element {
            number: 48,
            symbol: "Cd".to_string(),
            name: "Cadmium".to_string(),
            mass: 112.41,
            category: ElementCategory::TransitionMetal,
            position: (5, 12),
            description: "Soft, malleable, bluish-white metal. Used in batteries, pigments, and electroplating. Highly toxic.".to_string(),
        },
        Element {
            number: 49,
            symbol: "In".to_string(),
            name: "Indium".to_string(),
            mass: 114.82,
            category: ElementCategory::PostTransitionMetal,
            position: (5, 13),
            description: "Soft, malleable silvery-white metal. Used in touchscreens, flat-panel displays, and soldering alloys.".to_string(),
        },
        Element {
            number: 50,
            symbol: "Sn".to_string(),
            name: "Tin".to_string(),
            mass: 118.71,
            category: ElementCategory::PostTransitionMetal,
            position: (5, 14),
            description: "Silvery, malleable post-transition metal. Used in solder, tin plating, and bronze production.".to_string(),
        },
        Element {
            number: 51,
            symbol: "Sb".to_string(),
            name: "Antimony".to_string(),
            mass: 121.76,
            category: ElementCategory::Metalloid,
            position: (5, 15),
            description: "Lustrous, gray metalloid. Used in flame retardants, batteries, and electronics. Known since ancient times.".to_string(),
        },
        Element {
            number: 52,
            symbol: "Te".to_string(),
            name: "Tellurium".to_string(),
            mass: 127.60,
            category: ElementCategory::Metalloid,
            position: (5, 16),
            description: "Brittle, mildly toxic, silvery-white metalloid. Used in alloys and as a semiconductor in solar panels and electronics.".to_string(),
        },
        Element {
            number: 53,
            symbol: "I".to_string(),
            name: "Iodine".to_string(),
            mass: 126.90,
            category: ElementCategory::Halogen,
            position: (5, 17),
            description: "Purple-black crystalline solid that sublimes to a violet gas. Essential for thyroid hormones and used as a disinfectant.".to_string(),
        },
        Element {
            number: 54,
            symbol: "Xe".to_string(),
            name: "Xenon".to_string(),
            mass: 131.29,
            category: ElementCategory::NobleGas,
            position: (5, 18),
            description: "Colorless, dense, odorless noble gas. Used in lighting, ionization in plasma televisions, and as an anesthetic.".to_string(),
        },
        // Period 6 (part 1)
        Element {
            number: 55,
            symbol: "Cs".to_string(),
            name: "Cesium".to_string(),
            mass: 132.91,
            category: ElementCategory::AlkaliMetal,
            position: (6, 1),
            description: "Soft, gold-colored alkali metal. Extremely reactive. Used in atomic clocks, photoelectric cells, and catalyst in hydrogenation.".to_string(),
        },
        Element {
            number: 56,
            symbol: "Ba".to_string(),
            name: "Barium".to_string(),
            mass: 137.33,
            category: ElementCategory::AlkalineEarthMetal,
            position: (6, 2),
            description: "Soft, silvery alkaline earth metal. Used in drilling fluids, paints, and as a contrast agent in X-ray imaging.".to_string(),
        },
        Element {
            number: 57,
            symbol: "La".to_string(),
            name: "Lanthanum".to_string(),
            mass: 138.91,
            category: ElementCategory::Lanthanide,
            position: (6, 3),
            description: "Soft, malleable, silvery-white metal. Used in high-performance optical glasses and catalysts for petroleum refining.".to_string(),
        },
        Element {
            number: 72,
            symbol: "Hf".to_string(),
            name: "Hafnium".to_string(),
            mass: 178.49,
            category: ElementCategory::TransitionMetal,
            position: (6, 4),
            description: "Corrosion-resistant silvery gray metal. Used in nuclear reactor control rods and high-temperature alloys.".to_string(),
        },
        Element {
            number: 73,
            symbol: "Ta".to_string(),
            name: "Tantalum".to_string(),
            mass: 180.95,
            category: ElementCategory::TransitionMetal,
            position: (6, 5),
            description: "Hard, blue-gray, highly corrosion-resistant transition metal. Used in electronic components and surgical implants.".to_string(),
        },
        Element {
            number: 74,
            symbol: "W".to_string(),
            name: "Tungsten".to_string(),
            mass: 183.84,
            category: ElementCategory::TransitionMetal,
            position: (6, 6),
            description: "Extremely hard metal with the highest melting point of all elements. Used in light bulb filaments, cutting tools, and armor-piercing ammunition.".to_string(),
        },
        Element {
            number: 75,
            symbol: "Re".to_string(),
            name: "Rhenium".to_string(),
            mass: 186.21,
            category: ElementCategory::TransitionMetal,
            position: (6, 7),
            description: "One of the rarest elements in Earth's crust. Used in high-temperature superalloys for jet engines and catalysts.".to_string(),
        },
        Element {
            number: 76,
            symbol: "Os".to_string(),
            name: "Osmium".to_string(),
            mass: 190.23,
            category: ElementCategory::TransitionMetal,
            position: (6, 8),
            description: "Bluish-white, extremely dense, hard, brittle metal. Used in electrical contacts, fountain pen tips, and instrument pivots.".to_string(),
        },
        Element {
            number: 77,
            symbol: "Ir".to_string(),
            name: "Iridium".to_string(),
            mass: 192.22,
            category: ElementCategory::TransitionMetal,
            position: (6, 9),
            description: "Very hard, brittle, highly corrosion-resistant metal. Used in spark plugs, pen points, and crucibles for high-temperature reactions.".to_string(),
        },
        Element {
            number: 78,
            symbol: "Pt".to_string(),
            name: "Platinum".to_string(),
            mass: 195.08,
            category: ElementCategory::TransitionMetal,
            position: (6, 10),
            description: "Dense, malleable, precious, silver-white metal. Used in catalytic converters, laboratory equipment, and jewelry.".to_string(),
        },
        Element {
            number: 79,
            symbol: "Au".to_string(),
            name: "Gold".to_string(),
            mass: 196.97,
            category: ElementCategory::TransitionMetal,
            position: (6, 11),
            description: "Soft, dense, malleable, and ductile metal with bright yellow color. Used in jewelry, electronics, and as a reserve currency.".to_string(),
        },
        Element {
            number: 80,
            symbol: "Hg".to_string(),
            name: "Mercury".to_string(),
            mass: 200.59,
            category: ElementCategory::TransitionMetal,
            position: (6, 12),
            description: "Silvery liquid metal at room temperature. Used in thermometers, barometers, and electrical switches. Highly toxic.".to_string(),
        },
        Element {
            number: 81,
            symbol: "Tl".to_string(),
            name: "Thallium".to_string(),
            mass: 204.38,
            category: ElementCategory::PostTransitionMetal,
            position: (6, 13),
            description: "Soft, malleable gray post-transition metal. Used in electronics, specialized glass, and historically in rat poisons. Highly toxic.".to_string(),
        },
        Element {
            number: 82,
            symbol: "Pb".to_string(),
            name: "Lead".to_string(),
            mass: 207.2,
            category: ElementCategory::PostTransitionMetal,
            position: (6, 14),
            description: "Soft, malleable, heavy metal. Used in batteries, radiation shields, and historically in paints and gasoline. Toxic.".to_string(),
        },
        Element {
            number: 83,
            symbol: "Bi".to_string(),
            name: "Bismuth".to_string(),
            mass: 208.98,
            category: ElementCategory::PostTransitionMetal,
            position: (6, 15),
            description: "Brittle metal with a pinkish tinge. Used in pharmaceuticals, cosmetics, and low-melting alloys.".to_string(),
        },
        Element {
            number: 84,
            symbol: "Po".to_string(),
            name: "Polonium".to_string(),
            mass: 209.0,
            category: ElementCategory::Metalloid,
            position: (6, 16),
            description: "Radioactive metalloid that exists in nature in uranium ores. Used in anti-static devices and as a heat source in space satellites.".to_string(),
        },
        Element {
            number: 85,
            symbol: "At".to_string(),
            name: "Astatine".to_string(),
            mass: 210.0,
            category: ElementCategory::Halogen,
            position: (6, 17),
            description: "Radioactive halogen, rarest naturally occurring element in Earth's crust. No significant applications outside of research.".to_string(),
        },
        Element {
            number: 86,
            symbol: "Rn".to_string(),
            name: "Radon".to_string(),
            mass: 222.0,
            category: ElementCategory::NobleGas,
            position: (6, 18),
            description: "Radioactive, colorless, odorless, tasteless noble gas. Formed by the decay of radium and can accumulate in buildings. Health hazard.".to_string(),
        },
        // Period 7 (part 1)
        Element {
            number: 87,
            symbol: "Fr".to_string(),
            name: "Francium".to_string(),
            mass: 223.0,
            category: ElementCategory::AlkaliMetal,
            position: (7, 1),
            description: "Extremely rare, radioactive metal. Most unstable of the naturally occurring elements. No commercial applications.".to_string(),
        },
        Element {
            number: 88,
            symbol: "Ra".to_string(),
            name: "Radium".to_string(),
            mass: 226.0,
            category: ElementCategory::AlkalineEarthMetal,
            position: (7, 2),
            description: "Radioactive, silvery-white metal. Historically used in luminous paints and medical treatments. Highly radioactive.".to_string(),
        },
        Element {
            number: 89,
            symbol: "Ac".to_string(),
            name: "Actinium".to_string(),
            mass: 227.0,
            category: ElementCategory::Actinide,
            position: (7, 3),
            description: "Radioactive, silvery-white metallic element. Used as a neutron source and in thermoelectric power.".to_string(),
        },
        Element {
            number: 104,
            symbol: "Rf".to_string(),
            name: "Rutherfordium".to_string(),
            mass: 267.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 4),
            description: "Synthetic, radioactive transition metal. First transactinide element. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 105,
            symbol: "Db".to_string(),
            name: "Dubnium".to_string(),
            mass: 268.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 5),
            description: "Synthetic, radioactive transition metal. Named after the Russian town of Dubna. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 106,
            symbol: "Sg".to_string(),
            name: "Seaborgium".to_string(),
            mass: 269.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 6),
            description: "Synthetic, radioactive transition metal. Named after American nuclear chemist Glenn Seaborg. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 107,
            symbol: "Bh".to_string(),
            name: "Bohrium".to_string(),
            mass: 270.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 7),
            description: "Synthetic, radioactive transition metal. Named after Danish physicist Niels Bohr. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 108,
            symbol: "Hs".to_string(),
            name: "Hassium".to_string(),
            mass: 277.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 8),
            description: "Synthetic, radioactive transition metal. Named after the German state of Hesse. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 109,
            symbol: "Mt".to_string(),
            name: "Meitnerium".to_string(),
            mass: 278.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 9),
            description: "Synthetic, radioactive transition metal. Named after Austrian physicist Lise Meitner. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 110,
            symbol: "Ds".to_string(),
            name: "Darmstadtium".to_string(),
            mass: 281.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 10),
            description: "Synthetic, radioactive transition metal. Named after the German city of Darmstadt. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 111,
            symbol: "Rg".to_string(),
            name: "Roentgenium".to_string(),
            mass: 282.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 11),
            description: "Synthetic, radioactive transition metal. Named after Wilhelm Röntgen, discoverer of X-rays. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 112,
            symbol: "Cn".to_string(),
            name: "Copernicium".to_string(),
            mass: 285.0,
            category: ElementCategory::TransitionMetal,
            position: (7, 12),
            description: "Synthetic, radioactive transition metal. Named after astronomer Nicolaus Copernicus. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 113,
            symbol: "Nh".to_string(),
            name: "Nihonium".to_string(),
            mass: 286.0,
            category: ElementCategory::PostTransitionMetal,
            position: (7, 13),
            description: "Synthetic, radioactive element. Named after Japan (Nihon). Exists only in laboratories.".to_string(),
        },
        Element {
            number: 114,
            symbol: "Fl".to_string(),
            name: "Flerovium".to_string(),
            mass: 289.0,
            category: ElementCategory::PostTransitionMetal,
            position: (7, 14),
            description: "Synthetic, radioactive element. Named after the Flerov Laboratory in Russia. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 115,
            symbol: "Mc".to_string(),
            name: "Moscovium".to_string(),
            mass: 290.0,
            category: ElementCategory::PostTransitionMetal,
            position: (7, 15),
            description: "Synthetic, radioactive element. Named after the Moscow region. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 116,
            symbol: "Lv".to_string(),
            name: "Livermorium".to_string(),
            mass: 293.0,
            category: ElementCategory::PostTransitionMetal,
            position: (7, 16),
            description: "Synthetic, radioactive element. Named after Lawrence Livermore National Laboratory. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 117,
            symbol: "Ts".to_string(),
            name: "Tennessine".to_string(),
            mass: 294.0,
            category: ElementCategory::Halogen,
            position: (7, 17),
            description: "Synthetic, radioactive element. Named after the U.S. state of Tennessee. Exists only in laboratories.".to_string(),
        },
        Element {
            number: 118,
            symbol: "Og".to_string(),
            name: "Oganesson".to_string(),
            mass: 294.0,
            category: ElementCategory::NobleGas,
            position: (7, 18),
            description: "Synthetic, radioactive element. Named after Yuri Oganessian, a nuclear physicist. Exists only in laboratories.".to_string(),
        },
        // Lanthanides (Period 6, positions 4-18)
        Element {
            number: 58,
            symbol: "Ce".to_string(),
            name: "Cerium".to_string(),
            mass: 140.12,
            category: ElementCategory::Lanthanide,
            position: (8, 4),
            description: "Soft, silvery, reactive metal. Most abundant of the rare earth elements. Used in catalytic converters and for glass polishing.".to_string(),
        },
        Element {
            number: 59,
            symbol: "Pr".to_string(),
            name: "Praseodymium".to_string(),
            mass: 140.91,
            category: ElementCategory::Lanthanide,
            position: (8, 5),
            description: "Soft, silvery, malleable, and ductile metal. Used in special glasses, ceramics, and as a core material in carbon arc lighting.".to_string(),
        },
        Element {
            number: 60,
            symbol: "Nd".to_string(),
            name: "Neodymium".to_string(),
            mass: 144.24,
            category: ElementCategory::Lanthanide,
            position: (8, 6),
            description: "Silvery-white, rare-earth metal. Used in extremely strong permanent magnets and lasers.".to_string(),
        },
        Element {
            number: 61,
            symbol: "Pm".to_string(),
            name: "Promethium".to_string(),
            mass: 145.0,
            category: ElementCategory::Lanthanide,
            position: (8, 7),
            description: "Radioactive metallic element. Used in atomic batteries for spacecraft and medical devices.".to_string(),
        },
        Element {
            number: 62,
            symbol: "Sm".to_string(),
            name: "Samarium".to_string(),
            mass: 150.36,
            category: ElementCategory::Lanthanide,
            position: (8, 8),
            description: "Silvery rare-earth metal. Used in magnets, lasers, neutron capture, and in cancer treatments.".to_string(),
        },
        Element {
            number: 63,
            symbol: "Eu".to_string(),
            name: "Europium".to_string(),
            mass: 151.96,
            category: ElementCategory::Lanthanide,
            position: (8, 9),
            description: "Soft, silvery metal. Used as a phosphor activator in red and blue pigments for television and fluorescent lamps.".to_string(),
        },
        Element {
            number: 64,
            symbol: "Gd".to_string(),
            name: "Gadolinium".to_string(),
            mass: 157.25,
            category: ElementCategory::Lanthanide,
            position: (8, 10),
            description: "Silvery-white, malleable, and ductile rare-earth element. Used in MRI contrast agents, microwave applications, and data storage.".to_string(),
        },
        Element {
            number: 65,
            symbol: "Tb".to_string(),
            name: "Terbium".to_string(),
            mass: 158.93,
            category: ElementCategory::Lanthanide,
            position: (8, 11),
            description: "Silvery-white, rare earth metal. Used in solid-state devices, fuel cells, and as a dopant in calcium fluoride lasers.".to_string(),
        },
        Element {
            number: 66,
            symbol: "Dy".to_string(),
            name: "Dysprosium".to_string(),
            mass: 162.50,
            category: ElementCategory::Lanthanide,
            position: (8, 12),
            description: "Soft, silvery metal. Used in high-power magnets, nuclear reactor control rods, and data storage materials.".to_string(),
        },
        Element {
            number: 67,
            symbol: "Ho".to_string(),
            name: "Holmium".to_string(),
            mass: 164.93,
            category: ElementCategory::Lanthanide,
            position: (8, 13),
            description: "Relatively soft, malleable rare-earth metal. Has the highest magnetic strength of any element. Used in nuclear control rods and magnets.".to_string(),
        },
        Element {
            number: 68,
            symbol: "Er".to_string(),
            name: "Erbium".to_string(),
            mass: 167.26,
            category: ElementCategory::Lanthanide,
            position: (8, 14),
            description: "Silvery-white rare-earth metal. Used in fiber optic amplifiers, metallurgical applications, and nuclear reactors.".to_string(),
        },
        Element {
            number: 69,
            symbol: "Tm".to_string(),
            name: "Thulium".to_string(),
            mass: 168.93,
            category: ElementCategory::Lanthanide,
            position: (8, 15),
            description: "Bright, silvery-gray metal. The least abundant of the rare earth elements. Used in portable X-ray devices and lasers.".to_string(),
        },
        Element {
            number: 70,
            symbol: "Yb".to_string(),
            name: "Ytterbium".to_string(),
            mass: 173.05,
            category: ElementCategory::Lanthanide,
            position: (8, 16),
            description: "Soft, malleable, bright silvery metal. Used in memory devices, stainless steel, and as a dopant in optical fibers.".to_string(),
        },
        Element {
            number: 71,
            symbol: "Lu".to_string(),
            name: "Lutetium".to_string(),
            mass: 174.97,
            category: ElementCategory::Lanthanide,
            position: (8, 17),
            description: "Silvery-white rare-earth metal. Used in petroleum cracking catalysts, positron emission tomography, and specialty glass.".to_string(),
        },
        // Actinides (Period 7, positions 4-18)
        Element {
            number: 90,
            symbol: "Th".to_string(),
            name: "Thorium".to_string(),
            mass: 232.04,
            category: ElementCategory::Actinide,
            position: (9, 4),
            description: "Silvery, radioactive actinide metal. Used as nuclear fuel, in high-temperature ceramics, and in gas lantern mantles.".to_string(),
        },
        Element {
            number: 91,
            symbol: "Pa".to_string(),
            name: "Protactinium".to_string(),
            mass: 231.04,
            category: ElementCategory::Actinide,
            position: (9, 5),
            description: "Dense, radioactive actinide metal. No significant commercial applications due to high toxicity and radioactivity.".to_string(),
        },
        Element {
            number: 92,
            symbol: "U".to_string(),
            name: "Uranium".to_string(),
            mass: 238.03,
            category: ElementCategory::Actinide,
            position: (9, 6),
            description: "Silvery-white, dense, radioactive metal. Used in nuclear power generation, nuclear weapons, and as a colorant in glass.".to_string(),
        },
        Element {
            number: 93,
            symbol: "Np".to_string(),
            name: "Neptunium".to_string(),
            mass: 237.0,
            category: ElementCategory::Actinide,
            position: (9, 7),
            description: "Radioactive actinide metal, produced in nuclear reactors. Used in neutron detection equipment and as a precursor for plutonium.".to_string(),
        },
        Element {
            number: 94,
            symbol: "Pu".to_string(),
            name: "Plutonium".to_string(),
            mass: 244.0,
            category: ElementCategory::Actinide,
            position: (9, 8),
            description: "Radioactive, silvery-gray metal. Used in nuclear weapons, as reactor fuel, and in radioisotope thermoelectric generators.".to_string(),
        },
        Element {
            number: 95,
            symbol: "Am".to_string(),
            name: "Americium".to_string(),
            mass: 243.0,
            category: ElementCategory::Actinide,
            position: (9, 9),
            description: "Radioactive, synthetic metallic element. Used in smoke detectors, neutron sources, and thickness measurement devices.".to_string(),
        },
        Element {
            number: 96,
            symbol: "Cm".to_string(),
            name: "Curium".to_string(),
            mass: 247.0,
            category: ElementCategory::Actinide,
            position: (9, 10),
            description: "Radioactive, synthetic actinide. Used in scientific research and as an alpha particle source.".to_string(),
        },
        Element {
            number: 97,
            symbol: "Bk".to_string(),
            name: "Berkelium".to_string(),
            mass: 247.0,
            category: ElementCategory::Actinide,
            position: (9, 11),
            description: "Radioactive, synthetic actinide. Named after Berkeley, California. Used only in scientific research.".to_string(),
        },
        Element {
            number: 98,
            symbol: "Cf".to_string(),
            name: "Californium".to_string(),
            mass: 251.0,
            category: ElementCategory::Actinide,
            position: (9, 12),
            description: "Radioactive, synthetic actinide. Used in neutron moisture gauges, metal detectors, and cancer treatment.".to_string(),
        },
        Element {
            number: 99,
            symbol: "Es".to_string(),
            name: "Einsteinium".to_string(),
            mass: 252.0,
            category: ElementCategory::Actinide,
            position: (9, 13),
            description: "Radioactive, synthetic actinide named after Albert Einstein. Used only in scientific research.".to_string(),
        },
        Element {
            number: 100,
            symbol: "Fm".to_string(),
            name: "Fermium".to_string(),
            mass: 257.0,
            category: ElementCategory::Actinide,
            position: (9, 14),
            description: "Radioactive, synthetic actinide named after Enrico Fermi. Used only in scientific research.".to_string(),
        },
        Element {
            number: 101,
            symbol: "Md".to_string(),
            name: "Mendelevium".to_string(),
            mass: 258.0,
            category: ElementCategory::Actinide,
            position: (9, 15),
            description: "Radioactive, synthetic actinide named after Dmitri Mendeleev. Used only in scientific research.".to_string(),
        },
        Element {
            number: 102,
            symbol: "No".to_string(),
            name: "Nobelium".to_string(),
            mass: 259.0,
            category: ElementCategory::Actinide,
            position: (9, 16),
            description: "Radioactive, synthetic actinide named after Alfred Nobel. Used only in scientific research.".to_string(),
        },
        Element {
            number: 103,
            symbol: "Lr".to_string(),
            name: "Lawrencium".to_string(),
            mass: 266.0,
            category: ElementCategory::Actinide,
            position: (9, 17),
            description: "Radioactive, synthetic actinide named after Ernest Lawrence. Used only in scientific research.".to_string(),
        },
    ]
}

/// Get all elements organized for display in the periodic table layout
pub fn get_periodic_table_layout() -> Vec<Vec<Option<Element>>> {
    let elements = load_elements();
    let mut table = vec![vec![None; 18]; 10]; // Creating a 10x18 table

    for element in elements {
        let (row, col) = element.position;
        // Adjust for 0-indexed array
        if row > 0 && row <= 10 && col > 0 && col <= 18 {
            table[(row - 1) as usize][(col - 1) as usize] = Some(element);
        }
    }

    table
}